FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

COPY ["./src/Services/UserMS/User.API/User.API.csproj", "userapi/"]
COPY ["./src/Services/UserMS/Core/User.Domain/User.Domain.csproj", "domainproject"]
COPY ["./src/Services/UserMS/Core/User.Applicaton/User.Applicaton.csproj", "application/"]
COPY ["./src/Services/UserMS/Infrastructure/User.Persistence/User.Persistence.csproj", "infrastructure/persistence/"] 

RUN dotnet restore "userapi/User.API.csproj" 

COPY . .
WORKDIR "/app/userapi"
RUN dotnet build "User.API.csproj" -c Release -o /app/build

FROM build as publish
RUN dotnet publish "User.API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app 
COPY --from=publish /app/publish .

ENV DOTNET_TieredPGO 1 
ENV DOTNET_TC_QuickJitForLoops 1 
ENV DOTNET_ReadyToRun 0

ENTRYPOINT ["dotnet", "User.API.dll"]