FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app

COPY ./src/Services/UserMS/User.API/User.API.csproj .
COPY ./src/Services/UserMS/Core/User.Applicaton/User.Applicaton.csproj ./Core/User.Applicaton/

RUN dotnet restore 

COPY /src/Services/UserMS/User.API . 
COPY /src/Services/UserMS/Core/User.Applicaton/ .

RUN dotnet publish -c release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0

WORKDIR /app

COPY --from=build /app/out .

ENV DOTNET_TieredPGO 1 
ENV DOTNET_TC_QuickJitForLoops 1 
ENV DOTNET_ReadyToRun 0

ENTRYPOINT ["dotnet", "APIGateway.dll"]