FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

WORKDIR /app
COPY . .

RUN dotnet publish src/Services/UserMS/User.API/User.API.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
COPY --from=build-env /out .

ENV DOTNET_TieredPGO 1 
ENV DOTNET_TC_QuickJitForLoops 1 
ENV DOTNET_ReadyToRun 0

ENTRYPOINT dotnet User.API.dll